apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-claim
  namespace: sachs
  labels:
    app: mongo-pv-claim
    tier: database
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 16Gi
